Feature comments
GeiseR98/java-explore-with-me pull request #5
Opened 2023-08-04 15:35 UTC by GeiseR98

2023-08-04 21:30 UTC, db-exp requested changes

2023-08-04 21:30 UTC, db-exp commented on ewm-main-service/src/main/resources/application.properties
> -spring.datasource.url=${SPRING_DATASOURCE_URL}
может лучше вернуть?

2023-08-04 21:30 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/main/utility/Utility.java
а давай разобьем класс Utility - тут методы, которые вполне можно вынести в конкретные сервисы, чтобы не создавать страшный класс, который обо всех все знает

2023-08-04 22:00 UTC, GeiseR98 commented on ewm-main-service/src/main/resources/application.properties
> -spring.datasource.url=${SPRING_DATASOURCE_URL}
Я что то не очень понимаю как оно исчезло... Точнее знаю как оно исчезло (во время merge) но не понимаю как я это допустил)

2023-08-05 02:31 UTC, GeiseR98 commented on ewm-main-service/src/main/java/ru/practicum/main/utility/Utility.java
Мне показалось неплохой идеей создать класс который будет проверять некоторые кейсы и выдавать ошибки, это помогло избежать дублирования кода и убрало отвлекающий от бизнес логики код из сервисов. Да, я понимаю что в большом приложении такой класс стал бы огромным и не читаемым. Естественно, я прорефакторил, создав отдельные подсервисы каждого сервиса, дублирования кода появилось немного, а сервисы остались чистыми от работы с ошибками... Казалось бы все хорошо, но нет - появилась цикличность: eventService обращается к CategoryService что бы узнать существует ли категория, а CategoryService обращается к EventService что бы узнать свободна ли категория для удаления... В общем всё равно один из сервисов оказался "умнее" других)))

2023-08-05 11:55 UTC, db-exp approved these changes

2023-08-05 11:55 UTC, db-exp commented on ewm-main-service/src/main/java/ru/practicum/main/event/service/EventVerifier.java
> +    LocalDateTime validTimePublication(LocalDateTime createdOn, LocalDateTime eventDate, Integer difference) {
private/public ?  тут и ниже

2023-08-08 22:02 UTC, merged